### ISSUE TITLE
Dependency on ignore_msrs not documented

### ISSUE THREAD

**Issue by Toolybird** [Pavo-IM/Hackinabox#6]
Thanks for this, you've got some good stuff happening here with your methods.

I'm not on UnRaid but was attracted by the promise of "No need to use ANY of the AMD patches"

Unfortunately I found out the hard way that the guide does not work... unless the following is done:
```
# echo 1 > /sys/module/kvm/parameters/ignore_msrs
```
I can only assume UnRaid sets up ignore_msrs by default.

For the sake of the next person who comes along and puzzles endlessly over why macOS won't boot, please document the dependency on this kernel parameter. Thanks!

**Comment by Pavo-IM** [comment]
ignore_mars is only needed for kernel versions lower than 5.9.1 which is quite old.

**Comment by Toolybird** [comment]
> ignore_mars is only needed for kernel versions lower than 5.9.1 which is quite old

I'm not sure why you think that because it definitely doesn't match what I'm seeing. As stated above, I'm not using UnRaid. I'm on Arch using a 5.15.x kernel. If I use your config.list and EFI, macOS will not boot. If I then turn on ignore_msrs as detailed above, macOS now boots fine and I see this in the journal:
```
Nov 21 10:44:24 ryzen kernel: kvm [15736]: ignored rdmsr: 0x35 data 0x0
Nov 21 10:44:24 ryzen kernel: kvm [15736]: ignored rdmsr: 0x35 data 0x0
```
I'm curious. Please show the output of the following on your host system:
```
# cat /sys/module/kvm/parameters/ignore_msrs
```
Also, it would be interesting if you could perform a test by turning off ignore_msrs then see if your macOS VM still boots:
```
# echo 0 > /sys/module/kvm/parameters/ignore_msrs
```
Thanks

**Comment by Pavo-IM** [comment]
UnRaid set this automatically. That's the reason the guide is written for UnRaid.

**Comment by Toolybird** [comment]
> That's the reason the guide is written for UnRaid.

But why then direct[1] non-UnRaid folks here to use your guide?

It's only a 1 line addition to the guide so I'm surprised at the resistance. It's potentially wasting folks' time and in effect spreading misinformation by omission.

Anyway, I won't push it any further. Like I said, you've got some good info here. Thank you for your work and thanks for sharing.

[1] https://www.reddit.com/r/VFIO/comments/pnphuq/best_guide_to_install_macos_with_full_hardware/hl9hs4m/
