### ISSUE TITLE
l3 cache passthrough not working

### ISSUE THREAD

**Issue by Toolybird** [Pavo-IM/Hackinabox#7]
In the libvirt xml there is the following:
```
<cpu mode='host-passthrough' check='none' migratable='on'>
    <topology sockets='1' dies='1' cores='16' threads='2'/>
    <cache mode='passthrough'/>
    <feature policy='require' name='topoext'/>
  </cpu>
```
which is perfectly fine. But then further down is this:
```
<qemu:commandline>
    ...
    <qemu:arg value='-cpu'/>
    <qemu:arg value='host,vendor=GenuineIntel'/>
  </qemu:commandline>
```
The first XML chunk translates into a QEMU arg similar to this:
```
-cpu host,migratable=on,topoext=on,host-cache-info=on,l3-cache=off
```
The second translates into this:
```
-cpu host,vendor=GenuineIntel
```
This means 2 separate -cpu args are passed to QEMU and this is a big problem because the last one wins. The end result is that the contents of the first -cpu arg are lost.

Once the above issues are resolved, it turns out that macOS will not boot anyway. The only way I could get macOS to properly boot AND recognize host cache passthrough was by enabling 2 of the AMD Vanilla patches. Specifically,

algrey - Force cpuid_cores_per_package 12.0
algrey - _cpuid_set_cache_info - Set cpuid to 0x8000001D instead 4 - 10.13/10.14/10.15/11.0/12.0

Thanks

**Comment by Pavo-IM** [comment]
You are correct for the feature part in the cpu section of the xml, but the cache option isn’t part of the cpu feature set. All cpu features, cache and leaf 7 cpu features are passed through when adding the qemucommandline at the bottom, the only thing that gets changed is the vendor-id. Everything else is pulled directly from the CPUID. You do not need any kernel patches for AMD CPUs doing in this manner.

**Comment by Toolybird** [comment]
> All cpu features, cache and leaf 7 cpu features are passed through when adding the qemucommandline at the bottom

But that's not how QEMU command line argument parsing works. As stated above, if you pass multiple -cpu args to QEMU, the last one passed on the command line overrides the earlier ones. This can be easily demonstrated with a quick test using a Linux live CD equipped with lscpu.

I'm on Arch so I'm using the latest Arch installer. My host CPU is Ryzen 2700x. On bare metal, the relevant bits of lscpu output are as follows:
```
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 2700X Eight-Core Processor
...
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
...
L1d cache:                       256 KiB (8 instances)
L1i cache:                       512 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (2 instances)
...
```
This matches what is stated in the AMD specs[1]. Now, if I boot the Arch CD with QEMU with appropriate args eg:
```
-accel kvm
-cpu "host,topoext=on,host-cache-info=on,l3-cache=off"
-smp "16,sockets=1,dies=1,cores=8,threads=2"
```
The relevant bits of lscpu output from the VM look like this:
```
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
BIOS Vendor ID:                  QEMU
Model name:                      AMD Ryzen 7 2700X Eight-Core Processor
BIOS Model name:                 pc-q35-6.1
...
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
...
L1d cache:                       256 KiB (8 instances)
L1i cache:                       512 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (2 instances)
```
So far so good. The CPU and cache info are identical to bare metal. Now look what happens if I pass 2 -cpu args to QEMU with differing options;
```
-accel kvm
-cpu "host,topoext=on,host-cache-info=on,l3-cache=off"
-smp "16,sockets=1,dies=1,cores=8,threads=2"
-cpu "host,topoext=on"
```
```
...
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
BIOS Vendor ID:                  QEMU
Model name:                      AMD Ryzen 7 2700X Eight-Core Processor
BIOS Model name:                 pc-q35-6.1
...
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
...
L1d cache:                       512 KiB (8 instances)
L1i cache:                       512 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
```
See how the cache info is now subtly different? It is not using the passthrough cache info from the host. It is using the emulated cache info as provided by QEMU. The cache options from the first arg are lost. It becomes even clearer when studying the QEMU source. grep for cache_info_passthrough for the details and note especially this comment:
```
/* if true the CPUID code directly forward host cache leaves to the guest */
```
Back to the whole point of this report, inside macOS I'm seeing similar observations when looking at the output of:
```
# sysctl hw | grep cache
```
Maybe that's not the best way to interpret how macOS sees the cache info but it definitely shows differences when comparing  the differing QEMU -cpu args as outlined above.

[1] https://www.amd.com/en/products/cpu/amd-ryzen-7-2700x#product-specs

**Comment by Pavo-IM** [comment]
It would seem you are correct, but there isn't any performance benefit to passing it through and adding the 2 kernel patches you pointed out.
