### ISSUE TITLE
ACPI Sleep States s3 s4 s5

### ISSUE THREAD

**Issue by PudyJapan** [Pavo-IM/Hackinabox#8]
Hi,

I am facing the issue of ACPI Sleep States s3 s4 s5. I followed the steps except that I didn't enable the multifunction. I also created an image with the EFI to boot from it instead of modifying the usb EFI.

**Comment by Pavo-IM** [comment]
VMs shouldn't be set to sleep/wake. Disable sleep in the guest OS.

**Comment by PudyJapan** [comment]
> 

Thank you very much. Can you guide me how to do that? Shall I change the VM XML in someway or do something with unraid?

**Comment by Pavo-IM** [comment]
Google how to disable sleep in macOS. Its not a VM setting, its a OS setting.

**Comment by PudyJapan** [comment]
> 

Thank you but I am trying to launch the MAC OS installer. So there's no MAC that I would disable it's sleep.

**Comment by PudyJapan** [comment]
> Google how to disable sleep in macOS. Its not a VM setting, its a OS setting.

I mean I get this error trying to run the installer from USB or from a virtual disk

**Comment by Pavo-IM** [comment]
Ignore Sleep S3, S4 and S5 ACPI errors. These will not prevent you from installing macOS.

**Comment by PudyJapan** [comment]
> Ignore Sleep S3, S4 and S5 ACPI errors. These will not prevent you from installing macOS.

Thank you. But it seems to stop after printing the ACPI error then reboot. It never gets to the installer.

**Comment by Pavo-IM** [comment]
Then you have done something wrong. Use the config.plist in this repo and disable all SSDTs in the ACPI section of the config. Make sure to generate a SMBIOS and fill in the PlatformInfo section of the config first.
